### ISSUE TITLE
DynamicMap does not update when sending data via Pipe

### ISSUE THREAD

**Issue by bjoern1001001** [pyviz/holoviews#3376]
Hello all,

I am currently writing a (Python3) module that visualizes a dynamically changing graph using holoviews DynamicMap. For updating the plot I'm using a Pipe. 
Running this directly inside JupyterLab works without a problem, however creating the Pipe and the DynamicMap inside a class structure and returning it to JupyterLab sometimes works and sometimes doesn't update the visualization although the data has changed.

The code I'm currently using is like the following:
```
class View:
    def __init__(self):
        self.pipe = Pipe(data=[])
        self.map = hv.DynamicMap(hv.Graph, streams=[pipe]
    def show(self):
        return self.map
    def update(self, data):
        self.pipe.send(data)
```
update is called periodically from within another class.

Sometimes (pretty much randomly) this makes the DynamicMap update regularly as it is supposed to and sometimes, after restarting, it just freezes after the first update. Checking `self.map.streams` shows that the stream`s data has been changed.

I'd appreciate any help or hint in the right direction.

**Comment by philippjfr** [comment]
>Sometimes (pretty much randomly) this makes the DynamicMap update regularly as it is supposed to and sometimes, after restarting

Is this usually when displaying the plot the first time? I believe this might be due to a regression in the way plot cleanup is handled and was fixed in this PR: https://github.com/pyviz/pyviz_comms/pull/27

Could you try updating to the latest version of the Jupyterlab extension and then trying again?

**Comment by bjoern1001001** [comment]
Thanks for your reply.

I just tested multiple times and it does indeed only happen after a kernel restart or complete restart of JupyterLab.
Then I tried updating the JupyterLab extension by cloning the git repository and linking it. This unfortunately did not fix the problem. I could not find any noticeable differences using the latest repository version.

If there is anything else I should try or any more information is needed, please let me know.

**Comment by philippjfr** [comment]
>Then I tried updating the JupyterLab extension by cloning the git repository and linking it. 

I've already published a new release to npm, so you could just unlink again and install the latest using the usual command and then reload your JupyterLab tab. 

I had to make some minor fixes but can't reproduce any issues with this code:

```python
class View:
    def __init__(self):
        self.pipe = hv.streams.Pipe(data=[])
        self.map = hv.DynamicMap(hv.Graph, streams=[self.pipe]).opts(framewise=True, padding=0.1)
    def show(self):
        return self.map
    def update(self, data):
        self.pipe.send(data)
        
view = View()
view.show()

view.update(np.random.randint(0, 10, (10, 2)))
```

**Comment by bjoern1001001** [comment]
I used exactly that code and ran into the same issue. About 50% of my tries of running this after a kernel restart failed. Trying it for a second time without a restart however works without problems every time.

I'm doing this on Ubuntu 18.04 using a conda environment with Python 3.6.8, numpy 1.15.4, jupyterlab 0.35.4, holoviews 1.11.0, bokeh 1.0.3, pyviz_comms 0.7.0 and pyviz/jupyterlab_pyviz extension version 0.6.4.

Thanks a lot for investigating on this.

**Comment by philippjfr** [comment]
Can't reproduce this anymore.
